services:
  db:
    container_name: library-db
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: TEST_USER
      POSTGRES_PASSWORD: TEST_PASSWORD
      POSTGRES_DB: TEST_DB
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    container_name: library-api
    build:
      context: .
      target: runner
    ports:
      - '3000:3000'
      - '50051:50051'
    environment:
      - DB_URL=postgresql://TEST_USER:TEST_PASSWORD@db:5432/TEST_DB?schema=public
      - API_JWT_SECRET=secret
      - PORT=3000

    depends_on:
      - db
volumes:
  postgres_data:
