name: Deploy to VPS via SSH

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy en VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd /home/back/public_html/source

            pwd

            echo "Cloning or pulling changes"
            git clone git@github.com:LDA-en-Orbita/LDA-Back.git . || true

            git pull origin main

            echo "Creating image"
            docker stop back-lda || true
            docker rm back-lda || true

            docker build -t back-lda:latest .
            docker run -d -p 3003:3000 --name back-lda back-lda:latest
          EOF
